name: E2E Testing CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Configure Git to use HTTPS instead of SSH
        run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Start Live Server and Run Tests
        run: |
          npx http-server . -p 5500 -s &
          sleep 5
          npx nightwatch tests/loginTest.js --env chrome --headless
        env:
          NIGHTWATCH_HEADLESS: 1
